blank_issues_enabled: true
contact_links:
  - name: ❓ Ask a question
    url: https://discord.com/channels/996504201469366315/996504201968492547
    about: Ask questions about open source onboarding
    
