name: 🚀 New Feature
description: What do you want to have in this platform 💡
title: "Feature: "
labels: [enhancement]
assignees:  # Add this line
  - nsdhso
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    attributes:
      label: Desired solution
      description: Describe the solution you'd like.
    validations:
      required: true
  - type: input
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem or helpful links here.
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct Nothing right nows]()
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
